### ISSUE TITLE
Program is stuck

### ISSUE THREAD

**Issue by zhiyi1988** [SvenBaileyLab/HisTrader#2]
Hi, I have processed the files generated from three biological replicates. They all had the same format, and two of them worked fine. One was stuck and constantly showed "Use of uninitialized value $d_offset in seek at XXX/Histrader.pl line 411." It can generate output, but just cannot finish its work.

Normally, the end of the output file looks like this:
HiC_scaffold9   75906577        75906952        HiC_scaffold9:75906303-75907627 1       1
HiC_scaffold98  14504   14729   HiC_scaffold98:14182-17316      6       1
HiC_scaffold98  14904   15104   HiC_scaffold98:14182-17316      6       2
HiC_scaffold98  15204   15404   HiC_scaffold98:14182-17316      6       3
HiC_scaffold98  15704   15979   HiC_scaffold98:14182-17316      6       4
HiC_scaffold98  16054   16129   HiC_scaffold98:14182-17316      6       5
HiC_scaffold98  16654   17104   HiC_scaffold98:14182-17316      6       6

While the stuck one shows this:
HiC_scaffold9   73772143        73772293        HiC_scaffold9:73772038-73773442 3       1
HiC_scaffold9   73772468        73772643        HiC_scaffold9:73772038-73773442 3       2
HiC_scaffold9   73772918        73773043        HiC_scaffold9:73772038-73773442 3       3
HiC_scaffo

May I ask how to solve the problem?

Thanks, regards.

**Comment by SvenBaileyLab** [comment]
Hi,

I believe it may be that the script is failing on a peak that has no signal in the bedgraph. The script current expects to “see” signal, or data, within the peak region, since it is meant to process the called peaks from the same experiment.

Could you check to see if this is the case?The problematic peak should be the next one missing from the input. You could verify it in a browser. If you omit that peak it should continue.

This is something we will fix in the future and just return it as a missing.

Best regards
